<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-QMAKQJB" failures="1" tests="5" name="Test4" time="10.059" errors="0" timestamp="2024-07-23T14:25:23 IST">
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="userRegistaraionTest" time="1.477"/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="registartionConfirmationPage" time="1.812"/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightSearchTest" time="2.472"/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightSelectionTest" time="1.916"/>
  <testcase classname="com.vinGuru.tests.flightResevearion.FlightReseverationTest" name="flightReseverationConfirmationTest" time="1.819">
    <failure type="java.lang.AssertionError" message="expected [$2338 USD] but found [$584 USD]">
      <![CDATA[java.lang.AssertionError: expected [$2338 USD] but found [$584 USD]
at com.vinGuru.tests.flightResevearion.FlightReseverationTest.flightReseverationConfirmationTest(FlightReseverationTest.java:80)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1130)
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:630)
at java.base/java.lang.Thread.run(Thread.java:832)
... Removed 24 stack frames]]>
    </failure>
  </testcase> <!-- flightReseverationConfirmationTest -->
</testsuite> <!-- Test4 -->
